### ISSUE TITLE
https://www.tiktok.com/ still accessible from a browser

### ISSUE THREAD

**Issue by ghost** [gieljnssns/Social-media-Blocklists#1]
System: Pi-hole 5.0
Used link: https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/pihole-tiktok.txt

**Comment by gieljnssns** [comment]
Sorry for my very late response, can you try another time?

**Comment by dine909** [comment]
This is blocked for me - good job - would also like to say thanks!
