### ISSUE TITLE
adguard-tiktok.txt includes wrong domain

### ISSUE THREAD

**Issue by CzechJiri** [gieljnssns/Social-media-Blocklists#6]
[adguard-tiktok.txt](https://github.com/gieljnssns/Social-media-Blocklists/blob/master/adguard-tiktok.txt#L50) includes domain apps.mzstatic.com - this domain belongs to Apple Inc. and is used for official iOS app store listing

please see whois for more info https://www.whois.com/whois/mzstatic.com

**Comment by gieljnssns** [comment]
Thanks,
I removed it!
